backend:
  name: git-gateway
  branch: main # 你的主要分支名称
publish_mode: editorial_workflow # 开启内容审核工作流（可选）
media_folder: "public/uploads" # 定义图片上传的目录
collections:
  - name: "documents" # 你的内容集合名称
    label: "我的文档"
    folder: "_documents" # 文件在仓库中存放的目录
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "文件", name: "file", widget: "file"} # 使用 'file' widget 允许上传
      - {label: "描述", name: "body", widget: "markdown"}
